from django.db import models

from agrinova.constants import TAMIL_NADU_DISTRICTS


class PriceRecord(models.Model):
    """Historical (or synthetic) market price records."""

    crop = models.ForeignKey('marketplace.CropCategory', on_delete=models.CASCADE, related_name='price_records')
    district = models.CharField(max_length=50, choices=TAMIL_NADU_DISTRICTS)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    is_synthetic = models.BooleanField(
        default=False,
        help_text='True if generated by seed script (demo data)',
    )

    class Meta:
        ordering = ['date']
        unique_together = ('crop', 'district', 'date')
        indexes = [
            models.Index(fields=['crop', 'district', 'date']),
        ]

    def __str__(self):
        return f'{self.crop.name} @ {self.district} — ₹{self.price} ({self.date})'
